pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "Iam building the image in the docker swarn" '
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Iam Testing the image in the docker" '
            }
        }
        tage('Deploy') {
            steps {
                sh 'echo "Iam Deploying the image in the K8s" '
            }
        }
    }
}
